# Generated by Django 4.2.4 on 2023-08-24 19:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("photo", models.ImageField(blank=True, upload_to="speakers_photos")),
                ("name", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=100)),
                ("facebook", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpeakersVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("photo", models.ImageField(blank=True, upload_to="speakers_version_photos")),
                ("year", models.CharField(default=2023, max_length=4)),
            ],
            options={
                "verbose_name_plural": "Speakers Versions",
            },
        ),
        migrations.CreateModel(
            name="Advisors",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="speakers.basemodel",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("about_page", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Advisors",
                "ordering": ["-created_at"],
            },
            bases=("speakers.basemodel",),
        ),
        migrations.CreateModel(
            name="Speakers",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="speakers.basemodel",
                    ),
                ),
                ("home_page", models.BooleanField(default=False)),
                ("conference_page", models.BooleanField(default=False)),
                ("version", models.ManyToManyField(blank=True, to="speakers.speakersversion")),
            ],
            options={
                "verbose_name_plural": "Speakers",
                "ordering": ["-created_at"],
            },
            bases=("speakers.basemodel",),
        ),
    ]
