# Generated by Django 4.2.4 on 2023-09-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("speakers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakers",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
