# Generated by Django 4.2.5 on 2023-10-08 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("speakers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advisors",
            old_name="about_page",
            new_name="home_page",
        ),
    ]
