# Generated by Django 4.2.5 on 2024-01-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("speakers", "0002_rename_about_page_advisors_home_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speakersversion",
            name="year",
            field=models.CharField(default=2024, max_length=4),
        ),
    ]
