# Generated by Django 4.2.4 on 2023-09-07 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("speakers", "0002_speakers_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basemodel",
            old_name="address",
            new_name="country",
        ),
    ]
