# Generated by Django 4.2.5 on 2024-03-06 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentProject",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("project_status", models.CharField(max_length=100)),
                ("team_number", models.IntegerField()),
                ("university", models.CharField(max_length=100)),
                ("faculty", models.CharField(max_length=100)),
                ("project_name", models.CharField(max_length=100)),
                ("team_come_with", models.CharField(max_length=100)),
                ("project_abstract", models.TextField()),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
