# Generated by Django 4.2.5 on 2024-03-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentproject",
            name="submission_date",
            field=models.CharField(),
        ),
    ]
