# Generated by Django 4.2.5 on 2024-03-06 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("awards", "0002_alter_studentproject_submission_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentproject",
            name="submission_date",
        ),
    ]
