# Generated by Django 4.2.4 on 2023-08-24 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutConferenceImage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="about_conference_images/")),
            ],
            options={
                "verbose_name_plural": "About Conference Images",
            },
        ),
        migrations.CreateModel(
            name="ContractFile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="contract_files/")),
            ],
            options={
                "verbose_name_plural": "Contract Files",
            },
        ),
        migrations.CreateModel(
            name="ContractForm",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("industry", models.CharField(max_length=100)),
                ("interested_in", models.CharField(max_length=100)),
                ("contract_file", models.ManyToManyField(to="conference.contractfile")),
            ],
            options={
                "verbose_name_plural": "Contract Forms",
            },
        ),
    ]
