# Generated by Django 4.2.5 on 2023-09-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractfile",
            name="type",
            field=models.CharField(max_length=100),
        ),
    ]
