# Generated by Django 4.2.4 on 2023-08-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractfile",
            name="type",
            field=models.CharField(choices=[("one", "One"), ("two", "Two")], default="one", max_length=100),
            preserve_default=False,
        ),
    ]
