# Generated by Django 4.2.5 on 2024-03-06 09:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conference", "0002_alter_contractfile_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractform",
            name="interested_in",
        ),
    ]
