# Generated by Django 4.2.5 on 2024-01-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exhibitorversion",
            name="year",
            field=models.CharField(default=2024, max_length=4),
        ),
    ]
