# Generated by Django 4.2.5 on 2024-03-19 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitor", "0002_alter_exhibitorversion_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exhibitor",
            name="version",
        ),
        migrations.DeleteModel(
            name="ExhibitorVersion",
        ),
    ]
