# Generated by Django 4.2.5 on 2024-03-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitor", "0003_remove_exhibitor_version_delete_exhibitorversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibitor",
            name="exhibitor_url",
            field=models.URLField(blank=True),
        ),
    ]
