# Generated by Django 4.2.5 on 2024-03-19 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exhibitor", "0004_exhibitor_exhibitor_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exhibitor",
            name="is_partner",
        ),
        migrations.RemoveField(
            model_name="exhibitor",
            name="is_sponser",
        ),
        migrations.RemoveField(
            model_name="exhibitor",
            name="slider",
        ),
    ]
