# Generated by Django 4.2.5 on 2024-01-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_delete_floorplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerlink",
            name="media",
            field=models.ImageField(default=None, upload_to="register_links/"),
        ),
    ]
