# Generated by Django 4.2.5 on 2024-02-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_delete_floorplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerlink",
            name="type",
            field=models.CharField(
                choices=[
                    ("speaker", "Speaker"),
                    ("conference", "Conference"),
                    ("exhibitor", "Exhibitor"),
                    ("visitor", "Visitor"),
                    ("sponsor", "Sponsor"),
                    ("partner", "Partner"),
                    ("media", "Media"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
