# Generated by Django 4.2.5 on 2024-02-06 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PartnerAndSponser",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="partners_sponsrs/")),
                ("subtitle", models.CharField(blank=True, max_length=100, null=True)),
                ("link", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Partner and Sponser",
                "verbose_name_plural": "Partners and Sponsers",
            },
        ),
    ]
