# Generated by Django 4.2.5 on 2024-02-10 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("partners_sponsrs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorty",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RemoveField(
            model_name="partnerandsponser",
            name="category",
        ),
        migrations.AddField(
            model_name="partnerandsponser",
            name="category",
            field=models.ManyToManyField(blank=True, to="partners_sponsrs.categorty"),
        ),
    ]
