# Generated by Django 4.2.5 on 2024-02-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partners_sponsrs", "0002_categorty_remove_partnerandsponser_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partnerandsponser",
            name="category",
        ),
        migrations.AddField(
            model_name="partnerandsponser",
            name="category",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
