# Generated by Django 4.2.5 on 2023-10-14 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "email",
                    models.EmailField(
                        error_messages={"unique": "This email has already been used."}, max_length=254, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Mail",
                "verbose_name_plural": "Mails",
                "ordering": ("-created_at",),
            },
        ),
    ]
