# Generated by Django 4.2.5 on 2023-10-29 10:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_mail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AboutViews",
            new_name="ExhibitionViews",
        ),
    ]
