# Generated by Django 4.2.5 on 2023-10-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_rename_aboutviews_exhibitionviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=5)),
                ("registered_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
