# Generated by Django 4.2.5 on 2023-10-30 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_region"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TotalVisitor",
            new_name="HomeViews",
        ),
    ]
