# Generated by Django 4.2.5 on 2023-10-30 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_rename_totalvisitor_homeviews"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrationviews",
            options={"verbose_name": "Registration View", "verbose_name_plural": "Registration Views"},
        ),
    ]
