# Generated by Django 4.2.5 on 2023-10-31 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_alter_exhibitionviews_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homeviews",
            options={"verbose_name": "Home View", "verbose_name_plural": "Home Views"},
        ),
    ]
