# Generated by Django 4.2.5 on 2023-09-19 00:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID for this item",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Enter a title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Enter a brief description", max_length=1000, null=True),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="images/")),
            ],
            options={
                "verbose_name": "Visit",
                "verbose_name_plural": "Visits",
            },
        ),
        migrations.CreateModel(
            name="WhyVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID for this item",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(help_text="Enter a title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Enter a brief description", max_length=1000, null=True),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="images/")),
            ],
            options={
                "verbose_name": "Why to visit",
                "verbose_name_plural": "Why to visit",
            },
        ),
    ]
