# Generated by Django 4.2.5 on 2023-10-10 09:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscripeNews",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique ID for this item",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(help_text="Enter a first name", max_length=200)),
                ("last_name", models.CharField(help_text="Enter a last name", max_length=200)),
                ("email", models.EmailField(help_text="Enter a email", max_length=200)),
            ],
            options={
                "verbose_name": "Subscripe News",
                "verbose_name_plural": "Subscripe News",
            },
        ),
    ]
