# Generated by Django 4.2.5 on 2023-10-10 14:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0003_subscripenews_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterInterest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(help_text="Enter a email", max_length=200)),
                ("name", models.CharField(help_text="Enter a name", max_length=200)),
                ("job_title", models.CharField(help_text="Enter a job title", max_length=200)),
                ("company_name", models.CharField(help_text="Enter a company name", max_length=200)),
                ("address", models.CharField(help_text="Enter a address", max_length=200)),
                ("city", models.CharField(help_text="Enter a city", max_length=200)),
                ("country", models.CharField(help_text="Enter a country", max_length=200)),
                ("phone_number", models.CharField(help_text="Enter a phone number", max_length=200)),
                ("cell_phone", models.CharField(help_text="Enter a cell phone", max_length=200)),
                ("business_nature", models.CharField(help_text="Enter a business nature", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Register Interest",
                "verbose_name_plural": "Register Interest",
            },
        ),
        migrations.AlterField(
            model_name="subscripenews",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
