# Generated by Django 4.2.5 on 2023-10-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visit", "0005_registerinterest_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerinterest",
            name="interested_in",
            field=models.CharField(default="", help_text="Enter a interested in", max_length=200),
            preserve_default=False,
        ),
    ]
