# Generated by Django 4.2.4 on 2023-08-27 15:08

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                ("body", ckeditor.fields.RichTextField()),
                ("photo", models.ImageField(blank=True, upload_to="blog/%Y/%m/%d/")),
                ("bio", models.TextField(blank=True)),
                ("schedule", models.DateTimeField(blank=True, default=None, null=True)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("press_center", models.BooleanField(default=False, verbose_name="Prece Center Page")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Blogs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField()),
                ("photo", models.ImageField(blank=True, upload_to="news/%Y/%m/%d/")),
                ("link", models.URLField()),
                ("press_center", models.BooleanField(default=False, verbose_name="Prece Center Page")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "News",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonials",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=100)),
                ("photo", models.ImageField(blank=True, upload_to="testimonials/%Y/%m/%d/")),
                ("body", models.TextField()),
                ("youtube_link", models.URLField()),
                ("press_center", models.BooleanField(default=False, verbose_name="Prece Center Page")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Testimonials",
                "ordering": ["-created_at"],
            },
        ),
    ]
