# Generated by Django 4.2.5 on 2023-10-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="link",
            field=models.URLField(max_length=500),
        ),
    ]
