# Generated by Django 4.2.5 on 2023-09-19 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email1", models.EmailField(default="evis@nirvanaholding.com", max_length=254)),
                ("email2", models.EmailField(blank=True, default="event@nirvanaholding.com", max_length=254)),
                ("phone1", models.CharField(default="+55555 333 4444", max_length=20)),
                ("phone2", models.CharField(blank=True, default="+55555 333 4444", max_length=20)),
            ],
            options={
                "verbose_name_plural": "Contact",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location", models.URLField(default="https://www.google.com/maps/")),
            ],
            options={
                "verbose_name_plural": "Location",
            },
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("delegates", models.CharField(default=0)),
                ("speakers", models.CharField(default=0)),
                ("vehicles", models.CharField(default=0)),
                ("exhibitors", models.CharField(default=0)),
                ("country", models.CharField(default=0)),
            ],
            options={
                "verbose_name_plural": "Statistic",
            },
        ),
        migrations.CreateModel(
            name="Timer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", models.CharField(default=datetime.timedelta(seconds=1800))),
            ],
            options={
                "verbose_name_plural": "Timer",
            },
        ),
    ]
