# Generated by Django 4.2.5 on 2023-10-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="fax",
            field=models.CharField(blank=True, default="+55555 333 4444", max_length=20),
        ),
    ]
