# Generated by Django 4.2.5 on 2023-10-24 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_contact_fax"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
