# Generated by Django 4.2.5 on 2023-10-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_delete_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contact_type", models.CharField(max_length=100)),
                ("contact_value", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Contact",
                "unique_together": {("contact_type", "contact_value")},
            },
        ),
    ]
