# Generated by Django 4.2.5 on 2023-10-25 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statistic",
            old_name="vehicles",
            new_name="square_meters",
        ),
    ]
