# Generated by Django 4.2.5 on 2023-10-25 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_rename_vehicles_statistic_square_meters"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
